# sample rate for common config
sample_rate: 16000


# mel spectrogram configs
#
n_fft: 640
win_length: 640
hop_length: 321

#
window_fn: "torch.hamming_window"
center: True
pad_mode: "reflect"
power: 2.0
norm: "slaney"
n_mels: 81 # mel banks default
mel_scale: "slaney"

# trim audio configs librosa
top_db: 25