# common config
sample_rate: 16000
n_fft: 640
win_length: 640
hop_length: 321
window_fn: "torch.hamming_window"

# 
center: True
pad_mode: "reflect"
power: 2.0
norm: "slaney"
n_mels: 80 # mel banks default n_mels
mel_scale: "slaney"

# trim audio configs librosa
top_db: 25

# pitch shift audio torchaudio
pshift_bins_per_octave: 12
pshift_steps: 4