
# Convolution
# kernel size define sequentially
depthwise_kernel_size: 31
subsampling_kernel_size: 3
pointwise_kernel_size: 1
input_dims: 80
# cnn channel for conv subsampling
#channels: "[(1, 16), (16, 64)]"
channels: 1
subsampling_stride: 1 # subsampling stride 2
normal_stride: 1 # depthwise, pointwise
expansion_factor: 0.5

# define encoder dimension for MHA and model dimension depth
encoder_dim: 144 #
num_layers: 16

# LSTM
batch_first: True
# num clases out for linear deocder
num_classes: 29   # number of characters
decoder_dim: 144