
# Convolution
# kernel size define sequentially
kernel_size: 31

# cnn channel for conv subsampling
#channels: "[(1, 16), (16, 64)]"
input_dims: 80
channels: 1
subsampling_stride: 1 # subsampling stride 2
normal_stride: 1 # depthwise, pointwise

# define encoder dimension for MHA and model dimension depth
encoder_dim: 144 #
num_layers: 16

# LSTM
batch_first: True
# num clases out for linear deocder
#num_classes: 16360
num_classes: 27 # number of characters
decoder_dim: 144