
# Convolution
# kernel size define sequentially
kernel_size: "[(5,5), (3,3)]"

# cnn channel for conv subsampling
channels: "[(1, 16), (16, 64)]"
subsampling_stride: 2 # subsampling stride 2
normal_stride: 1 # depthwise, pointwise