
# Convolution
# kernel size define sequentially
kernel_size: "[(5,5), (3,3)]"

# cnn channel for conv subsampling
#channels: "[(1, 16), (16, 64)]"
channels: 81
subsampling_stride: 2 # subsampling stride 2
normal_stride: 1 # depthwise, pointwise

# define encoder dimension for MHA and model dimension depth
encoder_dim: 144 #

# LSTM
batch_first: True
# num clases out for linear deocder
num_classes: 200001